
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";
import { SessionProviderWrapper } from "@/utils/sessionContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html style={{backgroundColor:  "#2E2F37"}} lang="en">
      <body style={{padding: "20px", backgroundColor:  "#2E2F37"}} className={inter.className}>
        <AuthProvider>
        <SessionProviderWrapper>
          {children}
          </SessionProviderWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
